### ISSUE TITLE
App is gone :(

### ISSUE THREAD

**Issue by damixk** [edaku/app#1]
Byla to hezká sobota. 
Na stole čaj a někdo si hrál.
Přidal pár kouzel. 
Byl čas rollbacku a tak rm -rf dal.
Poté si vzpoměl, že není záloha. :disappointed:  
Od té doby již není žádná aplikace a já jsem nehoráznej ..:bamboo:... však víte jak je to dál.

**Comment by kubp** [comment]
To dokáže nasrat :D
Za týden to zvládneš udělat znovu.
Udělej jenom list itemu a detail itemu(stejně sem ještě neudělal api na login.

**Comment by damixk** [comment]
Jooo fakt? A co ta <b>404</b>

**Comment by kubp** [comment]
To je fičura. Prostě sem něco posral v configu. Klidně založ issue.

**Comment by damixk** [comment]
Jsem to, ale kouzelník. Applikačku jsem našel zahrabanou v realeasu. <img src="http://24.media.tumblr.com/fb02fb1830b6766598690e44e1257ad8/tumblr_mnsrcglBna1r24hxpo1_500.png"/>
